spring.application.name=EmployeeManagementSystem
spring.datasource.url=jdbc:postgresql://dpg-d95ulrdaeets73f3v24g-a/emps_kxdt
spring.datasource.username=emps_kxdt_user
spring.datasource.password=XLpvOz9i1lETlFJLHqe3AsvbNgpTZuUe

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true