spring.application.name=EmployeeManagementSystem
spring.datasource.url=jdbc:postgresql://dpg-d87ddu77f7vs73dg1i60-a.oregon-postgres.render.com:5432/emps_eyrc
spring.datasource.username=emps_eyrc_user
spring.datasource.password=VnMdG7m0hZzd3MqxFEN7HjAS80rTlm3Y
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect